### ISSUE TITLE
[Bug] : 네이버 앱이 없을 때, 크롬을 통한 로그인시 오류

### ISSUE THREAD

**Issue by SunnnySong** [hamhoney/flutter_naver_login_sdk#3]
1. When did bug occur?
- 기기에 네이버앱이 있다면 로그인이 가능합니다. 
- 기기에 네이버앱이 없어 크롬을 통해 로그인시 오류가 발생합니다.
    - 만약 크롬에 네이버로그인 기록이 없을 경우, 동의화면이 뜨고 여기서 OK를 누르면 다시 동의 페이지가 보여짐.
    - 크롬에 네이버로그인이 되어있을 경우, nid.naver.com~ 화면으로 잠깐 넘어갔다가 다시 앱으로 돌아와 errorCode:-1, message:user_cancel를 리턴합니다. 

2. Call me your OS.
Android

3. Show me console's log.
```text
[Paste console's log messages]
```

**Comment by hamhoney** [comment]
안녕하세요 @SunnnySong 님!
패키지를 이용해주셔서 감사합니다.

제 기억엔 네이버 앱 설치 유무를 확인하고 요청하는 로직이 SDK자체에서 문제를 갖고 있었습니다.

확인 후 다시 답변드리도록 하겠습니다.
좋은 하루 되세요🙂

**Comment by SunnnySong** [comment]
빠른 답변 감사합니다..! 저도 다른 방법이 있나 찾아보고 해결 방법이 있으면 달아두겠습니다. ㅎㅎ

**Comment by hamhoney** [comment]
@SunnnySong 님 좋은 아침입니다!


> 안녕하세요 @SunnnySong 님! 패키지를 이용해주셔서 감사합니다.
> 
> 제 기억엔 네이버 앱 설치 유무를 확인하고 요청하는 로직이 SDK자체에서 문제를 갖고 있었습니다.
> 
> 확인 후 다시 답변드리도록 하겠습니다. 좋은 하루 되세요🙂

웹, 앱 설치유무를 확인했던 것은 카카오 로그인이었네요😂
네이버 안드로이드 이슈 페이지에서도 동일한 현상을 문의한 글이 보입니다.
아쉽지만 Android SDK 에러이기 때문에 콜백 받는 부분을 제가 해결하기가 어렵겠습니다.

네이버 로그인 버튼 하단에 앱 설치를 권장하는 문구를 넣는 것은 어떨까요~?

**Comment by SunnnySong** [comment]
안녕하세요!
보내주신 코멘트 덕분에 네이버앱 미설치시 얼럿을 띄우는 형태로 변경했습니다. 추후 sdk 에러가 해결되면 수정해야겠네요. 감사합니다!

**Comment by hamhoney** [comment]
안녕하세요 @SunnnySong 님 NaverLoginSDK패키지를 이용해주셔서 다시 한 번 감사드립니다.
방금 전 `1.0.4`버전 업데이트로 **네이버 앱이 없는 상태**에서 네이버 로그인(`authenticate`함수)실행 시 errorCode return이 다음과 같이 표출되도록 수정하였습니다.

`OAuthLoginCallback`의 `onError`파라메터를 통해서 확인할 수 있습니다.
```text
errorCode:-1, message:기기에 네이버앱이 없습니다.
```

return을 받은 뒤 고객분들에게 안내문구를 표출하는 것이 안정적인 방법이 될 것 같습니다.
네이버팀에서 허락만 한다면 웹에서도 가능하도록 소스를 한 번 직접 수정해보아야겠네요.

새해 복 많이 받으시구요😉

**Comment by hamhoney** [comment]
안녕하세요 @SunnnySong 님! `2.2.0`버전부터는 Android에서 웹 로그인이 가능하도록 수정하였습니다. 좋은 하루 되세요😁
